### ISSUE TITLE
original indexes buffer?

### ISSUE THREAD

**Issue by giordi91** [syoyo/tinyobjloader#77]
Hi, I have been using this library for a while and is great! now I am trying to implement skincluster deformation , aka bone deformation on the geometry, 
I was already able to implement skeleton and animation out of maya into my program. Now I exported skin information per vertex out of maya.
The library due to be able to use a single index buffer for opengl (which is correct) duplicates some data, like vertex, uvs etc. The problem is that doing so I am not able to know what indexes the duplicated vertex come from so I cannot remap it to the original data. 
Would it be possible to generate extra buffers mapping to original points aswell? Basically the index buffer I would get if no duplication happened? I understand that this is extra data and not always useful. What about having an overloaded function or a flag that generates that data only if requested?

Is something you think would be possible to add in?

M.

**Comment by skurmedel** [comment]
Don't you have the id -> pos-data? All vertices with the same position index should be the same. Or do you have duplicate positions in the position buffer. Because that's unfortunately only solvable by consolidating points in the position buffer I think. 

But I am probably misinterpreting your problem :D Have a look at the develop branch, syoyo is working on a callback version I believe. Maybe that would solve your problem.

**Comment by giordi91** [comment]
![vertices](https://cloud.githubusercontent.com/assets/2525797/14939438/dbffac6a-0f3e-11e6-9602-4579890b2969.jpg)

Hi, here you can see the problem I am talking about, on the right you can see the actual obj (in this case a cube). 8 vertices should be read from it, also the other information i export from maya are based on the obj data, meaning i export extra data for vertices with index from 0-7. Now  since when I read the data with the library i get back 24 vertices, this mean that from index 8 to 23 I have no idea which one of the vertex got duplicated there. Meaning I have no way to rebuild it. What I actually need is the following: If you see in the right (the obj) the face indices are not the constant like 1/1/1 /2/2/2 3/3/3 after a while those triplest start to diverge and be mixed. What i need would be when the duplication of the vertices happen, to keep track of the original id.

Let me make you an example, meanwhile I read the data I figure out that I need to duplicate vertex 6, and that vertex 6 will become  vertex 21. Rather than just push back 21 to the index buffer , to keep separated buffer where instead of pushing 21, you push 6. In this way I know exactly what vertex was duplicated from and I can act accordingly. Otherwise I am blind, I have no idea which one are the vertex duplicated and to which original index they correspond to in the obj.

Hope that make sense.

M.

**Comment by syoyo** [comment]
Please use 'devel' branch. It reads vertex and index data mostly as is and does not generate duplicated(facevarying) vertex.

**Comment by giordi91** [comment]
thanks a lot I will have a look, is indeed possible to have both
behaviours? because that is what I am after, right now as it is perfect for
rendering, is just problematic do do other kind of geometry manipulation on
the data

On Sun, May 1, 2016 at 3:08 AM, Syoyo Fujita <notifications@github.com>
wrote:

> Please use 'devel' branch. It reads vertex and index data mostly as is and
> does not generate duplicated(facevarying) vertex.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/syoyo/tinyobjloader/issues/77#issuecomment-216008196>
>



-- 
Marco Giordano
R&D programmer at Double Negative
+447462721890
London(UK)
linkedin  <http://be.linkedin.com/in/marcogiordano3d/>

**Comment by syoyo** [comment]
No. current `master` has some problematic API design and data structure which is impossible to fix anymore without drastic changes.

`devel` branch has much clean and better loading of .obj but lacks testing and need some time to polish API design. You can contribute testing. After some tests, `devel` branch will become mainline(`master`)

**Comment by giordi91** [comment]
Hi I had a go to the latest develop and now i get out 24 values in the
vertices which looks correct 24/3 =8, so my 8 vertices. problem is now
indices comes out empty. size 0.
This is a snippet of code i am using:

std::vector<tinyobj::shape_t> shapes;
std::vector<tinyobj::material_t> materials;
tinyobj::attrib_t data;
string err;
tinyobj::LoadObj(&data, &shapes, &materials, &err, obj.c_str(), 0, false);
std::cout << "# of shapes : " << shapes.size() << std::endl;
std::cout << "err : " << err << std::endl;
Mesh* mesh = new Mesh(data, shapes[0]);

I am passing in reference to both attrib_t and shape_t, unluckily
shape_t.mesh.indices is empty. Am I doing something wrong or is a bug?

PS: now that the library doesn't do duplication any-more, how is it going
to work for rendering? since there wont be a single index buffer anymore
for all the vertex attribute. Is now on the user to massage the data and do
the duplication? or how do you see that working ?

M.

On Sun, May 1, 2016 at 12:11 PM, Syoyo Fujita <notifications@github.com>
wrote:

> No. current master has some problematic API design and data structure
> which is impossible to fix anymore without drastic changes.
>
> devel branch has much clean and better loading of .obj but lacks testing
> and need some time to polish API design. You can contribute testing. After
> some tests, devel branch will become mainline(master)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/syoyo/tinyobjloader/issues/77#issuecomment-216035243>
>



-- 
Marco Giordano
R&D programmer at Double Negative
+447462721890
London(UK)
linkedin  <http://be.linkedin.com/in/marcogiordano3d/>

**Comment by skurmedel** [comment]
@giordi91 ah sorry, I misunderstood :)

**Comment by giordi91** [comment]
thinking about the problem, if I am able to get 3 separated index buffer would be the best, like
points_Index, uv_index, normal_index. will do just fine. This will also allow me to easily build a single data buffer with interleaved data. I am gonan try to look in the code why the indices array  is coming out empty.

**Comment by syoyo** [comment]
`shape_t.mesh.index` was not filled correctly when `triangulate` flag was not set. Fixed in recent `develop` branch.

**Comment by giordi91** [comment]
i pulled this morning from develop and was still broken. anyway I am looking at the code and around line 590~:

`       index_t idx0, idx1, idx2;
        idx0.vertex_index = i0.v_idx;
        idx0.normal_index = i0.vn_idx;
        idx0.texcoord_index = i0.vt_idx;
        idx1.vertex_index = i1.v_idx;
        idx1.normal_index = i1.vn_idx;
        idx1.texcoord_index = i1.vt_idx;
        idx2.vertex_index = i2.v_idx;
        idx2.normal_index = i2.vn_idx;
        idx2.texcoord_index = i2.vt_idx;

        shape->mesh.indices.push_back(idx0);
        shape->mesh.indices.push_back(idx1);
        shape->mesh.indices.push_back(idx2);

        shape->mesh.num_vertices.push_back(3);
        shape->mesh.material_ids.push_back(material_id);
      }
    } else {
      for (size_t k = 0; k < npolys; k++) {
        index_t idx;
        idx.vertex_index = face[k].v_idx;
        idx.normal_index = face[k].vn_idx;
        idx.texcoord_index = face[k].vt_idx;
      }

      shape->mesh.num_vertices.push_back(static_cast<unsigned char>(npolys));
      shape->mesh.material_ids.push_back(material_id);  // per face
    }
  }

I can see the data i need are all there, do you think is possible to just have extra array to populate if requested?
something on the line:
position_idx.push_back(i0.v_idx);`
texcoord_idx.push_back(i0.vt_idx);
normals_idx.push_back(i0.vn_idx);

We can probably add all those to attrib_t and only get populate if a flag is set to true in LoadObj?
What are your thoughts on this?

M.

**Comment by giordi91** [comment]
I made a hotfix on my local version, I am passing in a reference to the attrib_t, which now holds 3 extra vectors for the 3 different indices. At this point the indices inside the shape are redundant.
Do you mind to elaborate a little what would be the final form of the api you had  in mind? and their data struct, I am not sure at the moment how the library handles multiple shapes since a single attrib struct is passed in.

M.

**Comment by syoyo** [comment]
You can craate your own mesh structure using callback API https://github.com/syoyo/tinyobjloader/tree/develop/examples/callback_api

**Comment by giordi91** [comment]
I had a look at the code, is a neat approach, the only thing i am a bit
worried about is performance side of things, getting that many function
call. any reason why you decide to go with such granularity rather than
passing out the raw buffers? (not a critic but a genuine curiosity)

On Tue, May 3, 2016 at 3:12 AM, Syoyo Fujita <notifications@github.com>
wrote:

> You can craate your own mesh structure using callback API
> https://github.com/syoyo/tinyobjloader/tree/develop/examples/callback_api
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/syoyo/tinyobjloader/issues/77#issuecomment-216417734>
>



-- 
Marco Giordano
R&D programmer at Double Negative
+447462721890
London(UK)
linkedin  <http://be.linkedin.com/in/marcogiordano3d/>

**Comment by syoyo** [comment]
First, you should benckmark it

Second, if you need absolute performance, you should use other .obj loader, e.g. assimp.

**Comment by giordi91** [comment]
agreed on the benchmark. I was wondering if could not we have a callback
for the bulk of data rather than the single bits. Anyway I have it working
now, i hacked the library but at one point i ll convert it to the callback
version.
I am having a bit of trouble to figure out how the multiple shapes are
called? Let say the obj holds two shapes? how from the callback I will be
able to know if I am still reading the first shape or the second one? That
is because I might have to handle them separately.

M.

On Tue, May 3, 2016 at 10:31 AM, Syoyo Fujita <notifications@github.com>
wrote:

> First, you should benckmark it
>
> Second, if you need absolute performance, you should use other .obj
> loader, e.g. assimp.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/syoyo/tinyobjloader/issues/77#issuecomment-216478778>
>



-- 
Marco Giordano
R&D programmer at Double Negative
+447462721890
London(UK)
linkedin  <http://be.linkedin.com/in/marcogiordano3d/>

**Comment by syoyo** [comment]
You are first better to learn .obj specification http://www.martinreddy.net/gfx/3d/OBJ.spec

**Comment by giordi91** [comment]
I think I am ok with the obj specification. My question was actually differentm. Before in your library you were writing into a vector of shapes, each shape contained all the relative data for that shape.
Now you are writing to an attribute struc which contained vertices etc etc , which is a single array how do i distinguish between vertices in different meshes inside the same obj? The same question extend to the callback side of things, you fire a callback each time a vertex/normal/uv is read, but I don't know to which shape the data correspond to, Might not be good for me to handle the whole geometry into a single triangle soup. Can you please tell me how to achieve data separation between shapes using the callback system?

**Comment by syoyo** [comment]
Do you really ok with .obj spec? If so, the answer should be obvious.
Anyway, great hint: There is a callback for 'g' and 'o'.

**Comment by giordi91** [comment]
my question has nothing to do with the specification of the obj :) I know what a group is, I just did not see the callback related, I would appreciate than rather then being detrimental of people asking question you could be more constructive, like one of the question you ignored in the other post was what was the purpose of the shape in the library if was not used anymore. All that plus me not seeing the callback for g led to the confusion and to my question. Things are always obvious for the designer of the code :). Anyway my question finally got answered and I can close the ticket. 

Cheers

**Comment by LYP951018** [comment]
I ran into this, too... I want to extract a vertex buffer and index buffer for each shape. Really, I don't think callback-based APIs are good for this...

**Comment by syoyo** [comment]
Vertex data is flattened and global.  Indices are reconstructed and allocated per mesh(shape_t). If you need vertex buffer for each shape, you need to extract vertices(`attrib_t::vertices`) using indices of a shape(`shape_t::mesh::indices`).
